apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deployment
  labels:
    app: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-app
        image: indalarajesh/spring-app:34-64d098be74e7104685167c16c583145f309e6a4a
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
