apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deployment
  labels:
    app: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-app
        image: indalarajesh/spring-app:31-dcdf0827352e3e0ab96b22956f268f7a8f7d4de3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
