apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deployment
  labels:
    app: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-app
        image: indalarajesh/spring-app:32-157815c0e72339fea425c2ffe080a5adcc06a227
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
