apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deployment
  labels:
    app: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-app
        image: indalarajesh/spring-app:42-def8d15e7a9cd1861cd2f4b826237ac4817d4f68
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
