apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  selector:
    app: spring-app
  type: LoadBalancer  # Change NodePort to LoadBalancer
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
